spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  web:
    resources:
      addMappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/blog
    username: blog
    password: testpassword1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  com.julymeltdown.blog: debug

app:
  jwt:
    secret: R7v#2A!tP$zW@9s&5kYqXfZrE*uHmKgN
    accessTokenExpirationMS: 86400000
    refreshTokenExpirationMS: 2592000000