spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    throwExceptionIfNoHandlerFound: true
  web:
    resources:
      addMappings: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/blog;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  com.julymeltdown.blog: debug
